// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw3A8QgdIqiL7JFWqNYCF7GsvxrLR1Ak0',
    appId: '1:419817963170:web:aaa9ebe24a415f90ee21fb',
    messagingSenderId: '419817963170',
    projectId: 'month4exam',
    authDomain: 'month4exam.firebaseapp.com',
    storageBucket: 'month4exam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4N5zQ9gwwksRSxcdrV_Sa1Plg4DDyLII',
    appId: '1:419817963170:android:2479555f2aac26e9ee21fb',
    messagingSenderId: '419817963170',
    projectId: 'month4exam',
    storageBucket: 'month4exam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKDrZ1exFypGz1tlEVLZ8PAIPiCqXc37g',
    appId: '1:419817963170:ios:a9c7f4b924d00f92ee21fb',
    messagingSenderId: '419817963170',
    projectId: 'month4exam',
    storageBucket: 'month4exam.appspot.com',
    iosBundleId: 'com.example.exam',
  );
}
